# Generated by Django 3.1.6 on 2021-06-21 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voluntarios', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='vol_ayuda',
            new_name='voluntario_o_solicita',
        ),
    ]
