# Generated by Django 3.1.6 on 2021-06-21 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voluntarios', '0002_auto_20210621_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rutUsuario',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Rut de usuario'),
        ),
    ]
